permalink: /:title/

authors:
  addy_osmani:
    name: Addy Osmani
    bio: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate, dolorem cum sapiente odio voluptates commodi. Pariatur, saepe, non id consequuntur voluptatum sequi illo esse dolor voluptatibus voluptates minus reiciendis veritatis aliquid quas.'
    gravatar: 96270e4c3e5e9806cf7245475c00b275
    email: addyosmani@gmail.com
    web: http://addyosmani.com
    twitter: addyosmani
    github: addyosmani
  dominic_cooney:
    name: Dominic Cooney
    bio: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate, dolorem cum sapiente odio voluptates commodi. Pariatur, saepe, non id consequuntur voluptatum sequi illo esse dolor voluptatibus voluptates minus reiciendis veritatis aliquid quas.'
    gravatar: bc648a000e8edf29f3b7310b68bac247
    email: dcooney@google.com
    web: http://dcooney.com
    twitter: dcooney
    github: dcooney
  eric_bidelman:
    name: Eric Bidelman
    bio: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate, dolorem cum sapiente odio voluptates commodi. Pariatur, saepe, non id consequuntur voluptatum sequi illo esse dolor voluptatibus voluptates minus reiciendis veritatis aliquid quas.'
    gravatar: e7948aac7c52b26470be80311873a398
    email: ericbidelman@google.com
    web: http://ericbidelman.com
    twitter: ebidel
    github: ebidel
  zeno_rocha:
    name: Zeno Rocha
    bio: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate, dolorem cum sapiente odio voluptates commodi. Pariatur, saepe, non id consequuntur voluptatum sequi illo esse dolor voluptatibus voluptates minus reiciendis veritatis aliquid quas.'
    gravatar: e190023b66e2b8aa73a842b106920c93
    email: hi@zenorocha.com
    web: http://zenorocha.com
    twitter: zenorocha
    github: zenorocha
